config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  resources :posts, only: [:new]
  resources :profiles, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/program_framework.rb
class ProgramFramework < ApplicationRecord
end

app/models/program_word.rb
class ProgramWord < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    # @word = Program_words.all
    # @framework = Program_frameworks.all
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/top.html.haml
= render "layouts/header"

.main
  .main-title1
    プログラミング言語
  .main-content1
    .main-content-block
      .title
        HTML
      .overview
        概要
      .text
        HyperText Markup Languageは、ハイパーテキストを記述するためのマークアップ言語の1つ

    .main-content-block
      .title
        CSS
      .overview
        概要
      .text
        Cascading Style Sheetsは、HTML や XML の要素をどのように修飾するかを指示する仕様の一つ

    .main-content-block
      .title
        Ruby
      .overview
        概要
      .text
        Rubyは、まつもとゆきひろにより開発されたオブジェクト指向スクリプト言語。
  .main-content2
    .main-content-block
      .title1
        javascript
      .overview
        概要
      .text
        プログラミング言語のひとつで,プロトタイプベースのオブジェクト指向スクリプト言語であるが、クラスなどのクラスベースに見られる機能も取り込んでいる。

    .main-content-block
      .title
        Haml
      .overview
        概要
      .text
        Hamlは、Webドキュメントにインラインコードを記述せずにHTMLをよりクリーンにするように設計されたテンプレートシステムです。

    .main-content-block
      .title
        SCSS
      .overview
        概要
      .text
        ハンプトン・キャトリンが設計しネイサン・バイゼンバウムが開発したスタイルシート言語である。

.main
  .main-title2
    フレームワーク
  .main-content2
    .main-content-block
      .title
        Ruby on Rails
      .overview
        概要
      .text
        Ruby on Railsは、オープンソースのWebアプリケーションフレームワークである。RoRまたは単にRailsと呼ばれる。その名にも示されているようにRubyで書かれている。

= render "layouts/footer"

app/views/layouts/_footer.html.haml
.footer
  .footer_info
    .footer_info_text
      管理者名
    .footer_info_name
      日野公介
    = link_to "プロフィール", profiles_path, class: "footer_profile"
  .footer_lastupdate
    .footer_lastupdate_text
      最終更新日時
    .footer_lastupdate_time
      2020-08-06

app/views/layouts/_header.html.haml
.header
  .header__title
    = link_to "プログラミング紹介サイト", root_path, class: "header__title--text"
  .header__right
    - if user_signed_in?
      = link_to "新規投稿", new_post_path, class: "header__right--btn"
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__right--btn"
    - else
      = link_to "ログイン", new_user_session_path, class: "header__right--btn"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ProgramApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/new.html.haml
= render "layouts/header"

.post-title
  学習したプログラム記事を作成

.form

= render "layouts/footer"

app/views/profiles/index.html.haml
.profile_title
  <管理者プロフィール>
.profile_name
  日野公介
.profile_age
  1989-04-21
.profile_birthplace
  徳島県